// ===== FILE START: apps/web/lib/games/gameModeTemplateOverrides.ts =====

import type { PlatformModeTemplateId } from "@/lib/games/modeTemplates";

export type GameModeTemplateOverride = {
  templateId: PlatformModeTemplateId;

  // preserve current live ids/slugs so routing/results do not break
  modeId: string;
  mode: string;

  // optional per-game UI overrides
  title?: string;
  subtitle?: string;
  players?: number;
  playersText?: string;
  entryFee?: number;
  prizePool?: number;
  limited?: boolean;
  durationMs?: number;
  requiresLevel?: number;
};

export const GAME_MODE_TEMPLATE_OVERRIDES: Record<
  string,
  GameModeTemplateOverride[]
> = {
  blackjack: [
    {
      templateId: "cash-starter",
      modeId: "bj-usd-080-limited",
      mode: "duel-arena-discounted",
      title: "Duel Arena Discounted",
      subtitle: "One time only!",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 0.8,
      prizePool: 1.5,
      limited: true,
      durationMs: 6 * 60 * 60 * 1000,
    },
    {
      templateId: "cash-standard",
      modeId: "bj-usd-100",
      mode: "duel-arena",
      title: "Duel Arena",
      subtitle: "Real match",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 1,
      prizePool: 1.5,
    },
    {
      templateId: "cash-high",
      modeId: "bj-usd-300",
      mode: "high-stakes-duel",
      title: "High Stakes Duel",
      subtitle: "Real match",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 3,
      prizePool: 4.5,
    },
    {
      templateId: "cash-apex",
      modeId: "bj-usd-500",
      mode: "apex-duel",
      title: "Apex Duel",
      subtitle: "Real match",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 5,
      prizePool: 7.5,
    },
    {
      templateId: "cash-bold",
      modeId: "bj-usd-1000",
      mode: "bold-duel",
      title: "Bold Duel",
      subtitle: "Real match",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 10,
      prizePool: 15,
    },
    {
      templateId: "practice-warmup",
      modeId: "bj-gems-050",
      mode: "warm-up",
      title: "Warm up",
      subtitle: "Practice-style",
      players: 1,
      entryFee: 50,
      prizePool: 120,
    },
    {
      templateId: "practice-medium",
      modeId: "bj-gems-1000",
      mode: "cash-factory",
      title: "Cash Factory",
      subtitle: "Practice-style",
      players: 10,
      playersText: "10 PLAYERS",
      entryFee: 1000,
      prizePool: 2000,
    },
  ],

  bingo: [
    {
      templateId: "cash-starter",
      modeId: "bingo-usd-050-limited",
      mode: "brawl-arena-discounted",
      title: "Brawl Arena Discounted",
      subtitle: "One time only!",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 0.5,
      prizePool: 3.8,
      limited: true,
      durationMs: 6 * 60 * 60 * 1000,
    },
    {
      templateId: "cash-standard",
      modeId: "bingo-usd-100",
      mode: "brawl-arena",
      title: "Brawl Arena",
      subtitle: "Real match",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 1,
      prizePool: 3.8,
    },
    {
      templateId: "cash-high",
      modeId: "bingo-usd-300",
      mode: "high-stakes-brawl",
      title: "High Stakes Brawl",
      subtitle: "Real match",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 3,
      prizePool: 11,
    },
    {
      templateId: "cash-apex",
      modeId: "bingo-usd-500",
      mode: "apex-brawl",
      title: "Apex Brawl",
      subtitle: "Real match",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 5,
      prizePool: 18,
    },
    {
      templateId: "cash-bold",
      modeId: "bingo-usd-1400",
      mode: "bold-brawl",
      title: "Bold Brawl",
      subtitle: "Real match",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 14,
      prizePool: 50,
    },
    {
      templateId: "practice-warmup",
      modeId: "bingo-gems-050",
      mode: "warm-up",
      title: "Warm up",
      subtitle: "Practice-style",
      players: 1,
      entryFee: 50,
      prizePool: 120,
    },
    {
      templateId: "practice-medium",
      modeId: "bingo-gems-1000",
      mode: "cash-factory",
      title: "Cash Factory",
      subtitle: "Practice-style",
      players: 10,
      playersText: "10 PLAYERS",
      entryFee: 1000,
      prizePool: 2000,
    },
  ],

  "block-puzzle": [
    {
      templateId: "cash-starter",
      modeId: "bp-usd-030-2p",
      mode: "starter-clash",
      title: "Starter Clash",
      subtitle: "Limited time only!",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 0.3,
      prizePool: 0.55,
      limited: true,
      durationMs: 6 * 60 * 60 * 1000,
    },
    {
      templateId: "cash-standard",
      modeId: "bp-usd-100-2p",
      mode: "quick-cash",
      title: "Quick Cash",
      subtitle: "Real match",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 1,
      prizePool: 1.8,
    },
    {
      templateId: "cash-high",
      modeId: "bp-usd-300-2p",
      mode: "high-stakes",
      title: "High Stakes",
      subtitle: "Real match",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 3,
      prizePool: 5.4,
      requiresLevel: 6,
    },
    {
      templateId: "cash-apex",
      modeId: "bp-usd-500-2p",
      mode: "apex-clash",
      title: "Apex Clash",
      subtitle: "Real match",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 5,
      prizePool: 9,
    },
    {
      templateId: "cash-bold",
      modeId: "bp-usd-1000-2p",
      mode: "bold-clash",
      title: "Bold Clash",
      subtitle: "Real match",
      players: 2,
      playersText: "2 PLAYERS",
      entryFee: 10,
      prizePool: 18,
    },
    {
      templateId: "practice-warmup",
      modeId: "bp-gems-050",
      mode: "warm-up",
      title: "Warm up",
      subtitle: "Practice-style",
      players: 1,
      entryFee: 50,
      prizePool: 120,
    },
    {
      templateId: "practice-medium",
      modeId: "bp-gems-200",
      mode: "speed-builder",
      title: "Speed Builder",
      subtitle: "Practice-style",
      players: 1,
      entryFee: 200,
      prizePool: 420,
    },
    {
      templateId: "practice-high",
      modeId: "bp-gems-500",
      mode: "board-master",
      title: "Board Master",
      subtitle: "Practice-style",
      players: 1,
      entryFee: 500,
      prizePool: 1050,
    },
  ],

  "reaction-tap": [
    {
      templateId: "cash-starter",
      modeId: "rt-usd-030-limited",
      mode: "starter-brawl",
      title: "Starter Brawl",
      subtitle: "Limited time only!",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 0.3,
      prizePool: 1.7,
      limited: true,
      durationMs: 6 * 60 * 60 * 1000,
    },
    {
      templateId: "cash-standard",
      modeId: "rt-usd-100",
      mode: "brawl-arena",
      title: "Brawl Arena",
      subtitle: "Real match",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 1,
      prizePool: 3.8,
    },
    {
      templateId: "cash-high",
      modeId: "rt-usd-300",
      mode: "high-stakes-brawl",
      title: "High Stakes Brawl",
      subtitle: "Real match",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 3,
      prizePool: 11,
    },
    {
      templateId: "cash-apex",
      modeId: "rt-usd-500",
      mode: "apex-brawl",
      title: "Apex Brawl",
      subtitle: "Real match",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 5,
      prizePool: 18,
    },
    {
      templateId: "cash-bold",
      modeId: "rt-usd-1400",
      mode: "bold-brawl",
      title: "Bold Brawl",
      subtitle: "Real match",
      players: 5,
      playersText: "5 PLAYERS",
      entryFee: 14,
      prizePool: 50,
    },
    {
      templateId: "practice-warmup",
      modeId: "rt-gems-050",
      mode: "warm-up",
      title: "Warm up",
      subtitle: "Practice-style",
      players: 1,
      entryFee: 50,
      prizePool: 120,
    },
    {
      templateId: "practice-medium",
      modeId: "rt-gems-1000",
      mode: "cash-factory",
      title: "Cash Factory",
      subtitle: "Practice-style",
      players: 10,
      playersText: "10 PLAYERS",
      entryFee: 1000,
      prizePool: 2000,
    },
  ],
};

export function getGameModeTemplateOverrides(
  gameId: string
): GameModeTemplateOverride[] {
  const gid = String(gameId || "").trim().toLowerCase();
  return GAME_MODE_TEMPLATE_OVERRIDES[gid] || [];
}

// ===== FILE END: apps/web/lib/games/gameModeTemplateOverrides.ts =====